/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cs2263.Project;

import Cs2263.UI.HomeUIViewController;
import Cs2263.UI.UIView;

import java.util.concurrent.TimeUnit;

public class App {





    public static void main(String[] args) throws Exception{
        UIView uiView = new UIView();
        uiView.startUI();


    }
}
