/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cs2263;

public class App {

    public static void main(String[] args) throws Exception{
        UIManager uiManager = UIManager.getInstance();
        uiManager.startUI();
    }

}
