/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cs2263;

import Cs2263.UI.UIManager;

public class App {

    public static void main(String[] args) throws Exception{

        // FUCK

        UIManager uiManager = UIManager.getInstance();
        uiManager.startUI();
    }

}
