/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cs2263.Project;

import Cs2263.App;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
    @Test void testTest(){
        assertTrue(true);
        assertFalse(false);
        assertEquals(0, 0);
    }

}
